version: '2'
services:
  ico:
    image: registry.jincor.com/backend/ico:latest
    build:
      context: ./
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
      - 4000:4000
    links:
      - auth
      - redis
      - verify
      - rpc
    depends_on:
      - rpc
    environment:
      ORM_ENTITIES_DIR: "dist/entities/**/*.js"
      ORM_SUBSCRIBER_DIR: "dist/subscriber/**/*.js"
      ORM_MIGRATIONS_DIR: "dist/migrations/**/*.js"
    networks:
      default:
        ipv4_address: 10.100.0.2

  auth:
    image: registry.jincor.com/backend/auth:latest
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      FORCE_HTTPS: disabled
      JWT_KEY: "uZrJ!xe*xN?!;oU.u*;QOSM+|=4C?WH?6eWPcK/6AkIXIVGQguSA*r"
      THROTTLER_WHITE_LIST: "127.0.0.1,10.100.0.2,10.100.0.6"
      TENANT_WHITE_LIST: "127.0.0.1,10.100.0.2,10.100.0.6"
    ports:
      - "3000"
      - "4000"
    links:
      - redis
    networks:
      default:
        ipv4_address: 10.100.0.3

  redis:
    image: registry.jincor.com/backend/redis:latest
    ports:
      - "6379"
    volumes:
      - ./storage/redis:/data
    networks:
      default:
        ipv4_address: 10.100.0.4

  rpc:
    image: registry.jincor.com/backend/ethereum-testrpc:latest
    build:
      context: ./
      dockerfile: rpc.Dockerfile
    ports:
      - "8545"
    volumes:
      - /root/ethereum-blockchain:/home/ethereum
    networks:
      default:
        ipv4_address: 10.100.0.5

  verify:
    image: registry.jincor.com/backend/verify:latest
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      THROTTLER_WHITE_LIST: "127.0.0.1,10.100.0.2,10.100.0.6"
      EMAIL_DRIVER: mailgun
      MAILGUN_DOMAIN: jincor.com
      MAILGUN_SECRET: key-176cd97e7ce70c9e75d826792669e53a
      MAILGUN_API_URI: https://api.mailgun.net/v3/
    links:
      - auth
      - redis
    networks:
      default:
        ipv4_address: 10.100.0.6

  mongo:
    image: registry.jincor.com/backend/mongodb:latest
    volumes:
        - ./storage/mongodb:/data/db
    networks:
      default:
        ipv4_address: 10.100.0.7
    ports:
      - "27017"
      - "28017"

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 10.100.0.0/16
          gateway: 10.100.0.1
