version: '2'
services:
  ico:
    image: registry.jincor.com/backend/ico:latest
    build:
      context: ./
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
      - 80:3000
    links:
      - rpc
    depends_on:
      - rpc
    volumes:
      - /root/ethereum-blockchain:/home/ethereum
    networks:
      default:
        ipv4_address: 10.100.0.2

  rpc:
    image: registry.jincor.com/backend/ethereum-testrpc:latest
    build:
      context: ./
      dockerfile: rpc.Dockerfile
    ports:
      - "8545"
    volumes:
      - /root/ethereum-blockchain:/home/ethereum
      - ./passwords:/passwords
    networks:
      default:
        ipv4_address: 10.100.0.5

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 10.100.0.0/16
          gateway: 10.100.0.1
